spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 956697621ok
    url: jdbc:mysql://192.168.31.140:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
